Updated README.md with OTEL environment variables
juliuskoval/NLog.Targets.OpenTelemetryProtocol pull request #18
Opened 2024-07-07 09:18 UTC by snakefoot

Resolves #17

2024-07-14 07:23 UTC, juliuskoval commented on README.md
> +- **UseHttp** : Determines whether logs are exported using gRPC or HTTP. (optional). When not specified it will use environment-variable: `OTEL_EXPORTER_OTLP_PROTOCOL`
I'd formulate the second sentence as 'When not specified, the protocol will be determined by the environment-variable: `OTEL_EXPORTER_OTLP_PROTOCOL`'. Also I'd mention that it is false by default

2024-07-14 07:30 UTC, juliuskoval commented on README.md
> +- **UseDefaultResources** : Exclude default ressource like: telemetry.sdk.name, telemetry.sdk.language and telemetry.sdk.version. When not specified it will use environment-variable: `OTEL_RESOURCE_A
This isn't quite true. I'd rewrite it like this:
Use default resources like: telemetry.sdk.name, telemetry.sdk.language and telemetry.sdk.version. By default true.
If set to true, resources will be determined by the environment variable OTEL_RESOURCE_ATTRIBUTES. Setting any resources manually wil override the environment variable.

2024-07-14 07:34 UTC, juliuskoval requested changes
a few changes

2024-07-14 09:49 UTC, snakefoot commented
Tried to improve the wording.

2024-07-22 06:51 UTC, merged

2024-07-22 06:51 UTC, juliuskoval commented
Merged.